on:
  push:
    branches:
      - dev
name: Deploy to CPanel
jobs:
  web-deploy:
    name: deploy Cpanel
    runs-on: ubuntu-latest
    steps:
      - name: get latest code
        uses: actions/checkout@v2.3.2

      - name: sync Code
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_ACCOUNT_DEV}}
          password: ${{secrets.FTP_PASSWORD_DEV}}
  